<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.auth</groupId>
        <artifactId>service-system</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>service-system-bootstrap</artifactId>
    <packaging>jar</packaging>

    <name>service-system-bootstrap</name>
    <description>系统服务启动与装配</description>

    <dependencies>
        <dependency>
            <groupId>com.auth</groupId>
            <artifactId>service-system-admin</artifactId>
        </dependency>
        <dependency>
            <groupId>com.auth</groupId>
            <artifactId>service-system-file</artifactId>
        </dependency>
        <dependency>
            <groupId>com.auth</groupId>
            <artifactId>service-system-schedule</artifactId>
        </dependency>
        <dependency>
            <groupId>com.auth</groupId>
            <artifactId>service-system-message</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>service-system</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>false</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
