<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.auth</groupId>
        <artifactId>auth-server-community</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>services</artifactId>
    <packaging>pom</packaging>

    <name>services</name>
    <description>服务模块</description>

    <modules>
        <module>service-auth</module>
        <module>service-system</module>
        <module>service-example</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.auth</groupId>
            <artifactId>common-starter-ip</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.auth</groupId>
            <artifactId>common-starter-resttemplate</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.auth</groupId>
            <artifactId>common-starter-webdoc</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.auth</groupId>
            <artifactId>module-platform-persistence</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.auth</groupId>
            <artifactId>common-mapstruct</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.auth</groupId>
            <artifactId>module-security-web-starter</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- 单元测试 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.restdocs</groupId>
            <artifactId>spring-restdocs-mockmvc</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- actuator -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- alibaba -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <!-- mapstruct -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
        </dependency>
    </dependencies>
</project>
