<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.auth</groupId>
        <artifactId>service-system</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>service-system-authorization</artifactId>
    <packaging>jar</packaging>

    <name>service-system-authorization</name>
    <description>授权失效 Outbox 与投递</description>

    <dependencies>
        <dependency>
            <groupId>com.auth</groupId>
            <artifactId>service-system-common</artifactId>
        </dependency>
    </dependencies>
</project>
